encoders:
    name: swin
    weights: "builder/weights/encoder.pth" # Optional: path to pretrained weights
    kwargs:
        img_size: [256, 256]
        patch_size: 2
        in_chans: 3
        embed_dims: [128, 192, 256, 320]
        depths: [2, 2, 6, 2]
        num_heads: [4, 6, 8, 10]
        window_size: 8
        mlp_ratio: 4.0
        qkv_bias: true
        norm_layer: LayerNorm

classifier:
    kwargs:
        encoder_dim: 320
        drop_rate: 0.1
        num_classes: 16
    weights: null

data:
    train_dir: "GenSC-Testbed/GT_Images_Classification/Train"
    test_dir: "GenSC-Testbed/GT_Images_Classification/Test"
    img_size: [256, 256]

training:
    num_epochs: 100
    batch_size: 32
    learning_rate: 0.0001
    weight_decay: 0.0001
    num_workers: 8
    checkpoint_dir: "checkpoints"
    scheduler:
        type: "CosineAnnealingLR"
        T_max: 50
        eta_min: 0.00001

decoders:
    name: swin
    weights: "build/weights/decoder.pth"
    kwargs:
        img_size: [256, 256]
        embed_dims: [320, 256, 192, 128]
        depths: [2, 6, 2, 2]
        num_heads: [10, 8, 6, 4]
        window_size: 8
        mlp_ratio: 4.0
        qkv_bias: true
        norm_layer: LayerNorm
        patch_norm: true

modulator:
    type: netaware
    auto_unit: true
    policy:
        type: logband
        B_min: 10.0
        B_max: 1000.0
        gamma: 2.0
        levels: [32, 64, 96, 128, 160, 192]
